NUMPY

In [3]:
import numpy as np

In [4]:
np.__version__

'2.4.4'

In [5]:
z =np.zeros(13)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
type(z)

numpy.ndarray

In [7]:
z= z.astype(int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
z.ndim

1

In [10]:
s = np.array([[1,2,2,2,3,4,5,6]])
s

array([[1, 2, 2, 2, 3, 4, 5, 6]])

In [11]:
s.ndim

2

In [12]:
two_dim = np.array([[1,3,4,5],[2,5,6,7]])
two_dim

array([[1, 3, 4, 5],
       [2, 5, 6, 7]])

In [13]:
two_dim.ndim

2

In [ ]:
sample =  np.array([[4,5,67,7],[4,1,9]])
sample

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
two_dim

array([[1, 3, 4, 5],
       [2, 5, 6, 7]])

In [ ]:
two_dim.shape #(row,column)

(2, 4)

In [ ]:
two_dim.reshape(8,)

array([1, 3, 4, 5, 2, 5, 6, 7])

In [19]:
two_dim.reshape(9,)

ValueError: cannot reshape array of size 8 into shape (9,)

In [20]:
two_dim.reshape(2,2,2)

array([[[1, 3],
        [4, 5]],

       [[2, 5],
        [6, 7]]])

In [21]:
two_dim.reshape(1,2,4)

array([[[1, 3, 4, 5],
        [2, 5, 6, 7]]])

In [22]:
two_dim.reshape(4,2,1)

array([[[1],
        [3]],

       [[4],
        [5]],

       [[2],
        [5]],

       [[6],
        [7]]])

In [25]:
s = two_dim.reshape(1,2,4,1,1,1)

In [26]:
s.ndim

6

In [27]:
s.size

8

In [35]:
a=np.array([[2,5,6],[6,5,8],[8,9,5]])
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [30]:
a[0][2]

np.int64(6)

In [33]:
a[-2][-1]

np.int64(8)

In [37]:
a[1:3,1:3]

array([[5, 8],
       [9, 5]])